version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: eve_money_dev_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eve_money_dev
    ports:
      - "5433:5432"
    volumes:
      - eve_money_dev_data:/var/lib/postgresql/data

volumes:
  eve_money_dev_data:
    name: eve_money_dev_data
