import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  ArrayMinSize,
  IsArray,
  IsIn,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Min,
  MinLength,
  ValidateNested,
} from 'class-validator';

export class ScriptConfirmBatchItemRequest {
  @ApiProperty({
    description: 'Cycle line ID',
    format: 'uuid',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  @IsUUID()
  lineId: string;

  @ApiProperty({
    description: 'Mode for this line update',
    enum: ['reprice', 'listing'],
    example: 'reprice',
  })
  @IsIn(['reprice', 'listing'])
  mode: 'reprice' | 'listing';

  @ApiProperty({
    description: 'Order quantity represented by this confirm',
    minimum: 0,
    example: 12,
  })
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  quantity: number;

  @ApiProperty({
    description: 'New unit price (required when mode=reprice).',
    required: false,
    minimum: 0.01,
    example: 123456.78,
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0.01)
  newUnitPrice?: number;

  @ApiProperty({
    description: 'Unit price (required when mode=listing).',
    required: false,
    minimum: 0.01,
    example: 123456.78,
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0.01)
  unitPrice?: number;
}

export class ScriptConfirmBatchFailedItemRequest {
  @ApiProperty({
    description:
      'Cycle line ID if known (optional for UI-level failures before line resolution).',
    format: 'uuid',
    required: false,
  })
  @IsOptional()
  @IsUUID()
  lineId?: string;

  @ApiProperty({
    description: 'Item name associated with the failure.',
    required: false,
    example: 'Tritanium',
  })
  @IsOptional()
  @IsString()
  @MinLength(1)
  itemName?: string;

  @ApiProperty({
    description: 'Human-readable failure reason from automation.',
    example: 'OCR mismatch after retries',
  })
  @IsString()
  @MinLength(1)
  reason: string;
}

export class ScriptConfirmBatchRequest {
  @ApiProperty({
    description:
      'Idempotency key generated by client for this location batch confirm.',
    example: 'run-2026-03-02T12:00Z-dodixie-reprice',
  })
  @IsString()
  idempotencyKey: string;

  @ApiProperty({
    description: 'List of successful UI updates to confirm.',
    type: [ScriptConfirmBatchItemRequest],
    required: false,
  })
  @IsOptional()
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => ScriptConfirmBatchItemRequest)
  updates?: ScriptConfirmBatchItemRequest[];

  @ApiProperty({
    description:
      'List of UI failures (not persisted as fees) for alerting/observability.',
    type: [ScriptConfirmBatchFailedItemRequest],
    required: false,
  })
  @IsOptional()
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => ScriptConfirmBatchFailedItemRequest)
  failedItems?: ScriptConfirmBatchFailedItemRequest[];
}
